### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by OSA413** [goshander/ydb-orm#1]
Привет! Спасибо за вклад в сообщество.
Чтобы другие могли использовать код этого репозитория (и, возможно, улучшать его), стоит добавить к нему файл лицензии.
Недавно Яндекс сам [открыл код Yandex Database под лицензией Apache 2.0](https://github.com/ydb-platform/ydb). Было бы круто, если другие разработчики могли использовать их БД с ORM.

Этот сайт может подсказать в выборе лицензии для кода:
https://choosealicense.com/
https://choosealicense.com/licenses/

**Comment by goshander** [comment]
Hi, LICENSE file was added
